# Generated by Django 5.0.2 on 2024-02-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customer_address_customer_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='User_Type',
        ),
    ]
