# Generated by Django 5.0.2 on 2024-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_customer_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='User_Type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Verifier', 'Verifier')], default='Customer', max_length=10),
        ),
    ]
