# Generated by Django 5.0.2 on 2024-02-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Description', models.TextField()),
                ('Visible', models.BooleanField(default=False)),
                ('Discription', models.CharField(blank=True, max_length=100)),
                ('Images', models.ImageField(upload_to='images')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
            ],
        ),
    ]
