# Generated by Django 5.0.2 on 2024-02-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(max_length=50)),
                ('Is_Email_Verified', models.BooleanField(default=False)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Is_Phone_Number_Verified', models.BooleanField(default=False)),
                ('Password', models.CharField(max_length=175)),
            ],
        ),
    ]
