# Generated by Django 5.0.2 on 2024-02-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_seller_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Is_Product_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
