# Generated by Django 5.0.2 on 2024-02-18 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_product_category_product_is_product_verified_and_more'),
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Verified_By',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='verifier.verifier_profile'),
        ),
    ]
