# Generated by Django 5.0.2 on 2024-02-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_product_product_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Seller/unverified Images'),
        ),
    ]
